
export const CHECK_ATTENDANCE_START = 'api/CHECK_ATTENDANCE_START';
export const CHECK_ATTENDANCE_SUCCESS = 'api/CHECK_ATTENDANCE_SUCCESS';
export const CHECK_ATTENDANCE_FAIL = 'api/CHECK_ATTENDANCE_FAIL';